version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
  app:
    build: .
    container_name: hubspot_api
    ports:
      - "8080:8080"
    depends_on:
      - redis
