server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          hubspot:
            client-id: "CLIENT_ID"
            client-secret: "SECRET_ID"
            scope: "crm.objects.contacts.write crm.objects.contacts.read"
            authorization-grant-type: "authorization_code"
            redirect-uri: "http://localhost:8080/auth/callback"
        provider:
          hubspot:
            authorization-uri: "https://app.hubspot.com/oauth/authorize"
            token-uri: "https://api.hubapi.com/oauth/v1/token"

  redis:
    host: localhost
    port: 6379

hubspot:
  webhook:
    client-secret: "SECRET_ID"

logging:
  level:
    org.springframework.web: DEBUG
